export const data = [
    {
        id: 'd2beb81e-2c8f-489f-885c-1318377c87c4',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Đang re',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb81e-2c8f-489f-885c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb81e-2c8f-489f-8s5c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-885c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8axe-2c8f-489f-885c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-885c-1318377c8az7c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-385c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-885c-1318377c57c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'a2beb8xe-2c8f-489f-885c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-885c-1313377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489x-x85c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2bea8xe-2c8f-489f-x85c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1318377c7c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-49f-x85c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-131377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1318377cxs87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-13ax377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1318azc87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2bxab8xe-2c8f-489f-x85c-1318377c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1318xa87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
    {
        id: 'd2beb8xe-2c8f-489f-x85c-1gfjhggb7c87c5',
        name: 'Jujutsu no Kaisen',
        describe: 'Phim hay cực hay luôn akakakakkaakakkakakakakakakakakakakak',
        status: 'Tạm dùng',
        author: ['haha', 'dd'],
        gerne: ['haha', 'dd'],
        director: ['haha', 'dd'],
        duration: 1800,
        videoType: [
            { title: 'Subs', episode: [] },
            { title: 'Thuyết minh', episode: [] },
        ].map((videoType) => videoType.title),
        releaseYear: '2020-05-18T14:10:30.000Z',
        country: 'Nhật Bổn',
        rating: 4.5,
    },
];
