// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    URL_Endpoint: string;
    APIKey: string;
    PUBLISH_KEY: string;
    PRIVATE_KEY: string;
    AUTH_SECRET: string;
    TIKTOKCOOKIE: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    FACEBOOK_CLENT_ID: string;
    FACEBOOK_CLIENT_SECRET: string;
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    URL_CLOUDFLARE_MODEL: string;
    CLOUDFLARE_AI_TOKEN: string;
}
